server:
  port: 8085

spring:
  application:
    name: FutureTravel

  sql:
    init:
      mode: always
      platform: mariadb
  datasource:
    password: futuretravel
    url: jdbc:mariadb://localhost:3306/Future_Travel
    username: futuretravel
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB10Dialect
    show-sql: true