server:
  port: 8085
  servlet:
    context-path: /gruppo8

spring:
  application:
    name: FutureTravel

  sql:
    init:
      mode: always
      platform: mariadb
  datasource:
    password: futuretravel
    url: jdbc:mysql://127.0.0.1:3306/future_travel?createDatabaseIfNotExist=true&autoReconnect=true
    username: futuretravel
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
      jakarta:
        persistence:
          sharedCache:
            mode: UNSPECIFIED
    show-sql: true
    open-in-view: true

