server:
  port: 8085

spring:
  application:
    name: FutureTravel

  sql:
    init:
      mode: always
      platform: mariadb
  datasource:
    password: 87!tyIlp?1
    url: jdbc:mariadb://18.102.24.178:3306/Future_Travel
    username: futuretravel
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
      jakarta:
        persistence:
          sharedCache:
            mode: UNSPECIFIED
    show-sql: true
    open-in-view: true